load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "ModuleZ",
    module_name = "ModuleZ",
    srcs = glob(["*.swift"]),
    visibility = ["//visibility:public"],
)