load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "AlamofireCopy",
    module_name = "AlamofireCopy",
    srcs = glob(["Source/*.swift", "Source/**/*.swift"]),
    visibility = ["//visibility:public"],
)